<?php
$data = array (
  'watermark_alpha' => 0,
  'integral_scale' => 0,
  'cache_time' => 0,
  'best_number' => 3,
  'new_number' => 3,
  'hot_number' => 3,
  'promote_number' => 3,
  'top_number' => 10,
  'history_number' => 5,
  'comments_number' => 5,
  'article_number' => 5,
  'page_size' => 10,
  'bought_goods' => 0,
  'goods_name_length' => 0,
  'top10_time' => 0,
  'goods_gallery_number' => 5,
  'no_picture' => 'images/no_picture.gif',
  'qq' => '',
  'ww' => '',
  'default_storage' => 1,
  'min_goods_amount' => 0,
  'one_step_buy' => 0,
  'invoice_type' => 0,
  'show_order_type' => 0,
  'help_open' => 1,
  'lang' => 'zh_cn',
  'integrate_code' => 'MSP',
);
?>